language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django18
    - python: 2.7
      env: TOXENV=quality
install:
  - pip install -r requirements/travis.txt
services:
  - mysql
  - rabbitmq
script:
  - tox
after_success:
  - coveralls
branches:
  only:
    - master
